### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by huanglei252** [sheerun/extracted-loader#1]
hi, I met this error when I use this loader.
![dingtalk20171229221537](https://user-images.githubusercontent.com/10335463/34439050-3669c18c-ece6-11e7-8a87-3d6f5f7db8ec.png)

**Comment by sheerun** [comment]
Could you post sample project and browser version you use?

**Comment by huanglei252** [comment]
I use Chrome, the version is 63.0.3239.84.

**Comment by sheerun** [comment]
It works for me on this browser. Could you post example project?

**Comment by kossnocorp** [comment]
It happens when the style isn't in the `head` but in the `body` (or somewhere else). Changing `document.head` → `document.body` helped me to make it work. https://github.com/sheerun/extracted-loader/blob/master/index.js#L10-L12

**Comment by sheerun** [comment]
@kossnocorp Maybe you want to prepare PR so it work for both head and body?

**Comment by kossnocorp** [comment]
@sheerun well, the loader doesn't fail with an exception but doesn't reload styles in my case because of CSS modules so I don't use it.

**Comment by sheerun** [comment]
I'll take it as a no

**Comment by kossnocorp** [comment]
Sorry 🤤
