### ISSUE TITLE
Allow setting prefix when using webpack-dev-server on another port

### ISSUE THREAD

**Issue by glebtv** [sheerun/extracted-loader#4]
Currently, prefix is hardcoded to document host+port:
https://github.com/sheerun/extracted-loader/blob/0fd1f685b4cab278d8824037b4282742fb869dc1/index.js#L26

reloading silently fails with no errors if webpack-dev-server is running on a different port than the page (this is a common setup with webpack-dev-server when used with a backend app).

For me, I changed it to ```document.location.hostname``` which gives localhost without port, and it works.

BTW, Thank you for a great plugin :+1:

**Comment by sheerun** [comment]
Do you want to send PR?

**Comment by glebtv** [comment]
PR sent https://github.com/sheerun/extracted-loader/pull/6.

**Comment by sheerun** [comment]
Should be release as 1.0.7 :)
